"use strict";
const defaults=[["Augusto Cury",3448569,20,50,"candidate"],["Ronaldo Caiado",2605148,20,60,"candidate"],["Renan Santos",2675887,60,10,"candidate"],["Romeu Zema",326488,0,80,"candidate"],["Votos nulos",3674249,45,20,"invalid"],["Votos brancos",2300798,33,20,"invalid"]];
const first={l:53879538,f:56104503,abs:33469244};
let entries=[],turnout={rate:0,l:50,f:50,i:0},result;
const $=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString("pt-BR"),percent=n=>n.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})+"%";
function reset(){entries=defaults.map(([name,votes,l,f,kind])=>({name,votes,l,f,kind}));turnout={rate:0,l:50,f:50,i:0};buildControls();calculate()}
function slider(label,value,min,max,attr){return '<div class="control"><label><span>'+label+'</span><strong>'+value+'%</strong></label><input type="range" min="'+min+'" max="'+max+'" value="'+value+'" '+attr+' aria-label="'+label+'"></div>'}
function buildControls(){for(const [kind,id] of [["candidate","candidateControls"],["invalid","invalidControls"]]){$(id).innerHTML=entries.map((e,index)=>e.kind!==kind?"":'<div class="candidate"><div class="candidate-head"><strong>'+e.name+'</strong><small>'+fmt(e.votes)+' votos</small></div><div class="sliders">'+slider("Lula",e.l,0,100-e.f,'data-index="'+index+'" data-side="l"')+slider("Flávio",e.f,0,100-e.l,'data-index="'+index+'" data-side="f"')+'</div><div class="remainder">Restante: '+(100-e.l-e.f)+'%</div><div class="mini"><i class="l" style="width:'+e.l+'%"></i><i class="f" style="width:'+e.f+'%"></i><i class="r" style="width:'+(100-e.l-e.f)+'%"></i></div></div>').join("")}buildTurnout()}
function buildTurnout(){$("turnoutControls").innerHTML='<div class="turnout-control">'+slider("Ausentes que retornam",turnout.rate,0,100,'data-turnout="rate"')+'</div><div class="sliders">'+slider("Para Lula",turnout.l,0,100,'data-turnout="l"')+slider("Para Flávio",turnout.f,0,100,'data-turnout="f"')+'</div>'+slider("Brancos ou nulos",turnout.i,0,100,'data-turnout="i"')+'<div class="mini"><i class="l" style="width:'+turnout.l+'%"></i><i class="f" style="width:'+turnout.f+'%"></i><i class="r" style="width:'+turnout.i+'%"></i></div>'}
function calculate(){let l=first.l,f=first.f,abs=first.abs,invalid=0;const rows=[{name:"Votos próprios",l:first.l,f:first.f,rest:0}];for(const e of entries){const el=Math.round(e.votes*e.l/100),ef=Math.round(e.votes*e.f/100),rest=e.votes-el-ef;l+=el;f+=ef;if(e.kind==="candidate")abs+=rest;else invalid+=rest;rows.push({name:e.name,l:el,f:ef,rest})}const returned=Math.round(first.abs*turnout.rate/100),rl=Math.round(returned*turnout.l/100),rf=Math.round(returned*turnout.f/100),ri=returned-rl-rf;l+=rl;f+=rf;abs-=returned;invalid+=ri;rows.push({name:"Retorno de ausentes",l:rl,f:rf,rest:ri});result={l,f,abs,invalid,rows};render()}
function render(){const {l,f,abs,invalid,rows}=result,valid=l+f,lp=l/valid*100,fp=f/valid*100;$("lTotal").textContent=fmt(l);$("fTotal").textContent=fmt(f);$("lPct").textContent=percent(lp);$("fPct").textContent=percent(fp);$("lBar").style.width=lp+"%";$("fBar").style.width=fp+"%";$("gap").textContent=fmt(Math.abs(l-f))+" votos";$("leader").textContent=l===f?"Empate no cenário":(l>f?"Lula":"Flávio Bolsonaro")+" à frente no cenário";$("valid").textContent=fmt(valid);$("abs").textContent=fmt(abs);$("invalid").textContent=fmt(invalid);$("pp").textContent=percent(Math.abs(lp-fp)).replace("%"," p.p.");const max=Math.max(l,f,60345999,58206354)*1.05;$("comparison").innerHTML=[["2022 · Lula",60345999,"lula"],["2022 · Jair Bolsonaro",58206354,"flavio"],["2026 · Lula (simulação)",l,"lula"],["2026 · Flávio (simulação)",f,"flavio"]].map(([name,v,color])=>'<div class="comparison-row"><div class="comparison-head"><span>'+name+'</span><strong>'+fmt(v)+'</strong></div><div class="track"><i class="'+color+'" style="width:'+(v/max*100)+'%"></i></div></div>').join("");$("rows").innerHTML=rows.map(r=>'<tr><td>'+r.name+'</td><td>'+fmt(r.l)+'</td><td>'+fmt(r.f)+'</td><td>'+fmt(r.rest)+'</td></tr>').join("")+'<tr><th>Total</th><th>'+fmt(l)+'</th><th>'+fmt(f)+'</th><th>—</th></tr>'}
document.addEventListener("input",ev=>{const el=ev.target;if(el.dataset.index!==undefined){const e=entries[Number(el.dataset.index)],side=el.dataset.side;e[side]=Math.min(Number(el.value),100-e[side==="l"?"f":"l"]);buildControls();calculate()}else if(el.dataset.turnout){const key=el.dataset.turnout,value=Number(el.value);turnout[key]=value;if(key==="l"){turnout.f=Math.min(turnout.f,100-value);turnout.i=100-value-turnout.f}else if(key==="f"){turnout.l=Math.min(turnout.l,100-value);turnout.i=100-value-turnout.l}else if(key==="i"){turnout.l=Math.min(turnout.l,100-value);turnout.f=100-value-turnout.l}buildTurnout();calculate()}});
document.querySelectorAll("nav button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b===btn));document.querySelectorAll(".tabcontent").forEach(s=>s.hidden=s.id!==btn.dataset.tab)}));
$("reset").addEventListener("click",reset);
$("csv").addEventListener("click",()=>{const data="Origem;Lula;Flávio;Restante\n"+result.rows.map(r=>[r.name,r.l,r.f,r.rest].join(";")).join("\n")+"\nTOTAL;"+result.l+";"+result.f+";";const url=URL.createObjectURL(new Blob(["\uFEFF"+data],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="simulador-eleitoral-2026.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$("copy").addEventListener("click",async()=>{const text="Simulador Eleitoral 2026\nLula: "+fmt(result.l)+"\nFlávio Bolsonaro: "+fmt(result.f)+"\nDiferença: "+fmt(Math.abs(result.l-result.f))+"\nCenário hipotético, não é previsão eleitoral.";try{await navigator.clipboard.writeText(text);$("status").textContent="Resumo copiado."}catch{$("status").textContent="Não foi possível copiar automaticamente."}});
reset();